---
# Example sealed secrets for O-RAN components
# These are encrypted with the cluster's public key
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oran-nlp-secrets
  namespace: oran-nlp
  labels:
    app.kubernetes.io/name: nlp-service
    app.kubernetes.io/component: nlp
    app.kubernetes.io/part-of: oran-intent-mano
spec:
  encryptedData:
    # These are example encrypted values - replace with real encrypted secrets
    api-key: AgCGc0JQlze...  # NLP model API key
    database-password: AgBgm5J2lki...  # Database password
    jwt-secret: AgCk8Xm9ppl...  # JWT signing secret
  template:
    metadata:
      name: oran-nlp-secrets
      namespace: oran-nlp
      labels:
        app.kubernetes.io/name: nlp-service
        app.kubernetes.io/component: nlp
        app.kubernetes.io/part-of: oran-intent-mano
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oran-orchestrator-secrets
  namespace: oran-orchestrator
  labels:
    app.kubernetes.io/name: orchestrator-service
    app.kubernetes.io/component: orchestrator
    app.kubernetes.io/part-of: oran-intent-mano
spec:
  encryptedData:
    # O2 API credentials
    o2-api-key: AgCgH9kLm5n...
    o2-api-secret: AgBwP8qRt7u...
    # Nephio/Porch credentials
    porch-token: AgCvZ3xYa2b...
    # Database credentials
    database-url: AgCfR5sKj8l...
    database-password: AgCmN4tGh6i...
    # TLS certificates
    tls-cert: AgCpQ7wEr9o...
    tls-key: AgCdF2vBn5m...
  template:
    metadata:
      name: oran-orchestrator-secrets
      namespace: oran-orchestrator
      labels:
        app.kubernetes.io/name: orchestrator-service
        app.kubernetes.io/component: orchestrator
        app.kubernetes.io/part-of: oran-intent-mano
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oran-ran-secrets
  namespace: oran-ran
  labels:
    app.kubernetes.io/name: ran-service
    app.kubernetes.io/component: ran
    app.kubernetes.io/part-of: oran-intent-mano
spec:
  encryptedData:
    # RAN component credentials
    cu-cp-cert: AgChM8rTy4s...
    cu-cp-key: AgBnL7qWe3r...
    cu-up-cert: AgCjK9pVa5d...
    cu-up-key: AgCgH6oUz2x...
    du-cert: AgCfR5sKj8l...
    du-key: AgCmN4tGh6i...
    # Configuration secrets
    plmn-id: AgCpQ7wEr9o...
    gnb-id: AgCdF2vBn5m...
  template:
    metadata:
      name: oran-ran-secrets
      namespace: oran-ran
      labels:
        app.kubernetes.io/name: ran-service
        app.kubernetes.io/component: ran
        app.kubernetes.io/part-of: oran-intent-mano
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oran-cn-secrets
  namespace: oran-cn
  labels:
    app.kubernetes.io/name: cn-service
    app.kubernetes.io/component: cn
    app.kubernetes.io/part-of: oran-intent-mano
spec:
  encryptedData:
    # 5G Core certificates
    amf-cert: AgChM8rTy4s...
    amf-key: AgBnL7qWe3r...
    smf-cert: AgCjK9pVa5d...
    smf-key: AgCgH6oUz2x...
    upf-cert: AgCfR5sKj8l...
    upf-key: AgCmN4tGh6i...
    # Database credentials
    mongodb-password: AgCpQ7wEr9o...
    mongodb-username: AgCdF2vBn5m...
    # Network configuration
    dnn-config: AgCeE1wQr8n...
    slice-config: AgCkK7tHg5j...
  template:
    metadata:
      name: oran-cn-secrets
      namespace: oran-cn
      labels:
        app.kubernetes.io/name: cn-service
        app.kubernetes.io/component: cn
        app.kubernetes.io/part-of: oran-intent-mano
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oran-tn-secrets
  namespace: oran-tn
  labels:
    app.kubernetes.io/name: tn-service
    app.kubernetes.io/component: tn
    app.kubernetes.io/part-of: oran-intent-mano
spec:
  encryptedData:
    # Network credentials
    ssh-private-key: AgChM8rTy4s...
    ssh-public-key: AgBnL7qWe3r...
    # Controller certificates
    ovn-cert: AgCjK9pVa5d...
    ovn-key: AgCgH6oUz2x...
    # VXLAN keys
    vxlan-key: AgCfR5sKj8l...
    # TC configuration
    tc-config: AgCmN4tGh6i...
  template:
    metadata:
      name: oran-tn-secrets
      namespace: oran-tn
      labels:
        app.kubernetes.io/name: tn-service
        app.kubernetes.io/component: tn
        app.kubernetes.io/part-of: oran-intent-mano
    type: Opaque
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oran-monitoring-secrets
  namespace: oran-monitoring
  labels:
    app.kubernetes.io/name: monitoring-service
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: oran-intent-mano
spec:
  encryptedData:
    # Grafana admin password
    grafana-admin-password: AgChM8rTy4s...
    grafana-admin-user: AgBnL7qWe3r...
    # Prometheus credentials
    prometheus-password: AgCjK9pVa5d...
    # Alertmanager configuration
    alertmanager-config: AgCgH6oUz2x...
    # SMTP credentials for alerts
    smtp-password: AgCfR5sKj8l...
    smtp-username: AgCmN4tGh6i...
    # TLS certificates
    monitoring-tls-cert: AgCpQ7wEr9o...
    monitoring-tls-key: AgCdF2vBn5m...
  template:
    metadata:
      name: oran-monitoring-secrets
      namespace: oran-monitoring
      labels:
        app.kubernetes.io/name: monitoring-service
        app.kubernetes.io/component: monitoring
        app.kubernetes.io/part-of: oran-intent-mano
    type: Opaque