# Kind cluster configuration for Central
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: central
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6446
  podSubnet: "10.247.0.0/16"
  serviceSubnet: "10.99.0.0/12"
  disableDefaultCNI: true
  kubeProxyMode: "iptables"

nodes:
- role: control-plane
  image: kindest/node:v1.28.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "cluster=central,site=central,zone=central-zone"
        node-ip: "172.21.0.2"
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    networking:
      podSubnet: "10.247.0.0/16"
      serviceSubnet: "10.99.0.0/12"
    apiServer:
      extraArgs:
        runtime-config: "api/all=true"
        enable-admission-plugins: "NodeRestriction,ResourceQuota,PodSecurityPolicy"
      certSANs:
      - "127.0.0.1"
      - "localhost"
      - "central-control-plane"
  extraMounts:
  - hostPath: /tmp/central-logs
    containerPath: /var/log
  - hostPath: /tmp/central-data
    containerPath: /var/lib/central
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30083
    protocol: TCP
  - containerPort: 30443
    hostPort: 30446
    protocol: TCP
  - containerPort: 6641
    hostPort: 6647
    protocol: TCP
  - containerPort: 6642
    hostPort: 6648
    protocol: TCP
  # Porch and Nephio ports
  - containerPort: 7007
    hostPort: 7007
    protocol: TCP
  - containerPort: 3000
    hostPort: 3001
    protocol: TCP

- role: worker
  image: kindest/node:v1.28.0
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "cluster=central,site=central,zone=central-zone,workload=mano"
        node-ip: "172.21.0.3"
  extraMounts:
  - hostPath: /tmp/central-worker1-logs
    containerPath: /var/log
  - hostPath: /tmp/central-worker1-data
    containerPath: /var/lib/worker

- role: worker
  image: kindest/node:v1.28.0
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "cluster=central,site=central,zone=central-zone,workload=o2"
        node-ip: "172.21.0.4"
  extraMounts:
  - hostPath: /tmp/central-worker2-logs
    containerPath: /var/log
  - hostPath: /tmp/central-worker2-data
    containerPath: /var/lib/worker

- role: worker
  image: kindest/node:v1.28.0
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "cluster=central,site=central,zone=central-zone,workload=porch"
        node-ip: "172.21.0.5"
  extraMounts:
  - hostPath: /tmp/central-worker3-logs
    containerPath: /var/log
  - hostPath: /tmp/central-worker3-data
    containerPath: /var/lib/worker

featureGates:
  "EphemeralContainers": true
  "PodSecurity": true