# Kind cluster configuration for Regional
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: regional
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6445
  podSubnet: "10.246.0.0/16"
  serviceSubnet: "10.98.0.0/12"
  disableDefaultCNI: true
  kubeProxyMode: "iptables"

nodes:
- role: control-plane
  image: kindest/node:v1.28.0
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "cluster=regional,site=regional,zone=regional-zone"
        node-ip: "172.20.0.2"
  - |
    kind: ClusterConfiguration
    metadata:
      name: config
    networking:
      podSubnet: "10.246.0.0/16"
      serviceSubnet: "10.98.0.0/12"
    apiServer:
      extraArgs:
        runtime-config: "api/all=true"
        enable-admission-plugins: "NodeRestriction,ResourceQuota,PodSecurityPolicy"
      certSANs:
      - "127.0.0.1"
      - "localhost"
      - "regional-control-plane"
  extraMounts:
  - hostPath: /tmp/regional-logs
    containerPath: /var/log
  - hostPath: /tmp/regional-data
    containerPath: /var/lib/regional
  extraPortMappings:
  - containerPort: 30080
    hostPort: 30082
    protocol: TCP
  - containerPort: 30443
    hostPort: 30445
    protocol: TCP
  - containerPort: 6641
    hostPort: 6645
    protocol: TCP
  - containerPort: 6642
    hostPort: 6646
    protocol: TCP

- role: worker
  image: kindest/node:v1.28.0
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "cluster=regional,site=regional,zone=regional-zone,workload=cn"
        node-ip: "172.20.0.3"
  extraMounts:
  - hostPath: /tmp/regional-worker1-logs
    containerPath: /var/log
  - hostPath: /tmp/regional-worker1-data
    containerPath: /var/lib/worker

- role: worker
  image: kindest/node:v1.28.0
  kubeadmConfigPatches:
  - |
    kind: JoinConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "cluster=regional,site=regional,zone=regional-zone,workload=mec"
        node-ip: "172.20.0.4"
  extraMounts:
  - hostPath: /tmp/regional-worker2-logs
    containerPath: /var/log
  - hostPath: /tmp/regional-worker2-data
    containerPath: /var/lib/worker

featureGates:
  "EphemeralContainers": true
  "PodSecurity": true